#!/usr/bin/env bash
#
# verifyHyperProver.sh
#
# Verifies deployed HyperProver contracts on blockchain explorers using Foundry's verify-contract.
# Reads deployment data from the CSV file generated by deployHyperProverWithCreateX.ts.
#
# Features:
# - Supports verification on multiple chains with different API keys
# - Retries verification on failure with a delay
# - Provides detailed logging and summary statistics
# - Handles constructor arguments correctly
#
# Environment variables:
# - HYPERPROVER_RESULTS_FILE: Path to the CSV file with deployment results (default: out/hyperprover_deployments.csv)
# - ETHERSCAN_API_KEY: API key for all block explorers (Etherscan, Basescan, Arbiscan, etc.)
#
# CSV format expected:
# ChainID,ContractName,ContractAddress,Mailbox,Portal,ConstructorArgs,Success,Error

set -e

# Load environment variables from .env, prioritizing existing env vars
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/utils/load_env.sh"
load_env

# Default results file
RESULTS_FILE="${HYPERPROVER_RESULTS_FILE:-out/hyperprover_deployments.csv}"

# Verify deployment data exists
if [ ! -f "$RESULTS_FILE" ]; then
  echo "❌ Error: Deployment data file not found at $RESULTS_FILE"
  echo "Please run deployHyperProverWithCreateX.ts first to deploy contracts and generate deployment data."
  exit 1
fi

# Check for API key
if [ -z "$ETHERSCAN_API_KEY" ]; then
  echo "❌ Error: ETHERSCAN_API_KEY not set in .env"
  exit 1
fi

echo "🔍 HyperProver Contract Verification"
echo "===================================="
echo "Results file: $RESULTS_FILE"
echo "API Key: ${ETHERSCAN_API_KEY:0:8}..."
echo ""

# Check if first line contains CSV headers and skip it
FIRST_LINE=$(head -n 1 "$RESULTS_FILE")
START_LINE=1
if [[ "$FIRST_LINE" == *"ChainID"*"ContractAddress"* ]]; then
  echo "📝 CSV header detected, skipping header line"
  START_LINE=2
fi

# Count total contracts to verify
TOTAL_CONTRACTS=$(tail -n +$START_LINE "$RESULTS_FILE" | wc -l | tr -d ' ')

echo "📊 Found $TOTAL_CONTRACTS contract(s) to verify"
echo ""

# Create temp file for tracking results
TEMP_RESULTS=$(mktemp)
echo "0,0" > "$TEMP_RESULTS"  # successful,failed

# Process each deployed contract
CURRENT_CONTRACT=0
while IFS=, read -r CHAIN_ID CONTRACT_NAME CONTRACT_ADDRESS MAILBOX PORTAL CONSTRUCTOR_ARGS SUCCESS ERROR; do
  # Increment contract counter
  CURRENT_CONTRACT=$((CURRENT_CONTRACT + 1))

  echo "🔄 Verifying contract ($CURRENT_CONTRACT of $TOTAL_CONTRACTS): $CONTRACT_NAME"
  echo "   Chain ID: $CHAIN_ID"
  echo "   Address: $CONTRACT_ADDRESS"

  # Skip if deployment failed
  if [ "$SUCCESS" = "false" ]; then
    echo "   ⚠️  Skipping - deployment failed: $ERROR"
    # Increment failed counter
    COUNTERS=$(cat "$TEMP_RESULTS")
    SUCCESSFUL=$(echo "$COUNTERS" | cut -d',' -f1)
    FAILED=$(echo "$COUNTERS" | cut -d',' -f2)
    echo "$SUCCESSFUL,$((FAILED + 1))" > "$TEMP_RESULTS"
    echo ""
    continue
  fi

  # Build verification command
  VERIFY_CMD="forge verify-contract"
  VERIFY_CMD+=" --chain $CHAIN_ID"
  VERIFY_CMD+=" --etherscan-api-key \"$ETHERSCAN_API_KEY\""
  VERIFY_CMD+=" --watch"

  # Add constructor args if not empty
  if [ -n "$CONSTRUCTOR_ARGS" ] && [ "$CONSTRUCTOR_ARGS" != "0x" ]; then
    echo "   🧩 Using constructor arguments"
    VERIFY_CMD+=" --constructor-args \"$CONSTRUCTOR_ARGS\""
  else
    echo "   📝 No constructor arguments"
  fi

  VERIFY_CMD+=" \"$CONTRACT_ADDRESS\" \"contracts/prover/HyperProver.sol:HyperProver\""

  # Execute verification command
  echo "   📝 Executing verification..."
  eval "$VERIFY_CMD"

  VERIFY_RESULT=$?
  # Note: forge returns 0 even when contract is already verified
  if [ $VERIFY_RESULT -eq 0 ]; then
    echo "   ✅ Verification succeeded for $CONTRACT_NAME on chain $CHAIN_ID"
    # Increment successful counter
    COUNTERS=$(cat "$TEMP_RESULTS")
    SUCCESSFUL=$(echo "$COUNTERS" | cut -d',' -f1)
    FAILED=$(echo "$COUNTERS" | cut -d',' -f2)
    echo "$((SUCCESSFUL + 1)),$FAILED" > "$TEMP_RESULTS"
  else
    echo "   ❌ Verification failed for $CONTRACT_NAME on chain $CHAIN_ID"
    echo "   🔄 Retrying verification in 5 seconds..."
    sleep 5

    # Retry once
    eval "$VERIFY_CMD"
    VERIFY_RESULT=$?

    if [ $VERIFY_RESULT -eq 0 ]; then
      echo "   ✅ Verification succeeded on retry for $CONTRACT_NAME on chain $CHAIN_ID"
      # Increment successful counter
      COUNTERS=$(cat "$TEMP_RESULTS")
      SUCCESSFUL=$(echo "$COUNTERS" | cut -d',' -f1)
      FAILED=$(echo "$COUNTERS" | cut -d',' -f2)
      echo "$((SUCCESSFUL + 1)),$FAILED" > "$TEMP_RESULTS"
    else
      echo "   ❌ Verification failed again for $CONTRACT_NAME on chain $CHAIN_ID"
      # Increment failed counter
      COUNTERS=$(cat "$TEMP_RESULTS")
      SUCCESSFUL=$(echo "$COUNTERS" | cut -d',' -f1)
      FAILED=$(echo "$COUNTERS" | cut -d',' -f2)
      echo "$SUCCESSFUL,$((FAILED + 1))" > "$TEMP_RESULTS"
    fi
  fi

  echo ""
done < <(tail -n +$START_LINE "$RESULTS_FILE")

# Read final counts from temp file
COUNTERS=$(cat "$TEMP_RESULTS")
SUCCESSFUL_VERIFICATIONS=$(echo "$COUNTERS" | cut -d',' -f1)
FAILED_VERIFICATIONS=$(echo "$COUNTERS" | cut -d',' -f2)
rm -f "$TEMP_RESULTS"

# Display verification summary
echo "📊 Verification Summary:"
echo "Total contracts processed: $TOTAL_CONTRACTS"
echo "Successfully verified: $SUCCESSFUL_VERIFICATIONS"
echo "Failed to verify: $FAILED_VERIFICATIONS"

if [ $SUCCESSFUL_VERIFICATIONS -eq $TOTAL_CONTRACTS ]; then
  echo "✅ All contracts were successfully verified!"
  exit 0
else
  if [ $SUCCESSFUL_VERIFICATIONS -gt 0 ]; then
    echo "⚠️  Some contracts were verified, but others failed. Check the logs for details."
    exit 1
  else
    echo "❌ No contracts could be verified. Check the logs for details."
    exit 1
  fi
fi
