name: Eco Routes Protocol CI Tests

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: echo "::set-output name=my_output::my_value"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use Variable
        run: echo "${{ steps.step1.outputs.my_output }}"
    
  # lint:
  #   name: Eslint, prettier and solhint
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4

  #     - name: install node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version-file: ".nvmrc"
  #         cache: "yarn"

  #     - name: install dependencies
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: install # will run `yarn install` command

  #     - name: build project
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: build # will run `yarn build` command

  #     - name: check lint
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: format # will run `yarn format` command

  # tests:
  #   name: Test Suite
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: checkout code
  #       uses: actions/checkout@v4

  #     - name: install node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version-file: ".nvmrc"
  #         cache: "npm"

  #     - name: install dependencies
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: install # will run `yarn install` command

  #     - name: build project
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: build # will run `yarn build` command

  #     - name: Run Test
  #       uses: borales/actions-yarn@v4
  #       with:
  #         cmd: test # will run `yarn test` command
