name: Eco Routes Protocol CI Tests

on: [push]

jobs:
  lint:
    name: Eslint, prettier and solhint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: install node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: build project
        uses: borales/actions-yarn@v5
        with:
          cmd: build # will run `yarn build` command

      - name: check lint
        uses: borales/actions-yarn@v5
        with:
          cmd: format # will run `yarn format` command

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo Following files are changed...
            git status

            echo Changes:
            git diff

            exit 1;
          else
            exit 0;
          fi

  tests:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2

      - name: install node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: install dependencies
        uses: borales/actions-yarn@v5
        with:
          cmd: install # will run `yarn install` command

      - name: build project
        uses: borales/actions-yarn@v5
        with:
          cmd: build # will run `yarn build` command

      - name: Run Test
        uses: borales/actions-yarn@v5
        with:
          cmd: test # will run `yarn test` command
